title:            Quentin Fayet
description:
disqus_shortname:
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: https://mmistakes.github.io, http://yourdomain.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:

# Owner/author information
owner:
  name:           Quentin Fayet
  avatar:         quentinfayet.jpg
  bio:            "Passionate R&D engineer, eating, coding, sleeping."
  email:          fayet.quentin@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  facebook:
  github:         quentinfayet
  stackexchange:
  linkedin:       quentin-fayet
  instagram:      quentinfayet
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    	Europe/Paris
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

liquid_pdflatex:
  debug: false
  density: 300
  resize: 300x300
  usepackages: tikz
  output_directory: /_latex
  latex_cmd: "pdflatex -interaction=nonstopmode -output-directory $output-directory $texfile > /dev/null 2>&1"
  pdfcrop_cmd: "pdfcrop $pdffile $pdffile > /dev/null 2>&1"
  convert_cmd: "convert -fuzz 10% -transparent white -density $density $resize_opt $pdffile $pngfile  > /dev/null 2>&1"

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
